# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-14 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_external_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externaldatasource',
            old_name='slug',
            new_name='identifier',
        ),
    ]
