# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-14 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_external_data', '0002_auto_20191114_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldatasource',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
