# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-14 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_external_data', '0004_externaldatasource_export_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDataRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=1024)),
                ('requested', models.DateTimeField()),
                ('sources', models.ManyToManyField(related_name='requests', to='passive_data_kit_external_data.ExternalDataSource')),
            ],
        ),
    ]
