# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-21 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_external_data', '0005_externaldatarequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldatasource',
            name='token',
            field=models.CharField(default='abc123', max_length=1024),
            preserve_default=False,
        ),
    ]
