# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-21 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_external_data', '0007_auto_20191120_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externaldatasource',
            name='token',
        ),
        migrations.AddField(
            model_name='externaldatarequest',
            name='token',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
