# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-21 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_external_data', '0008_auto_20191120_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDataRequestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False)),
                ('data_file', models.FileField(upload_to='pdk_external_files/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='passive_data_kit_external_data.ExternalDataRequest')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='passive_data_kit_external_data.ExternalDataSource')),
            ],
        ),
    ]
