# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-21 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_external_data', '0009_externaldatarequestfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldatarequestfile',
            name='uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now()),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='externaldatarequestfile',
            name='processed',
        ),
        migrations.AddField(
            model_name='externaldatarequestfile',
            name='processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
