# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_external_data', '0010_auto_20191120_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldatasource',
            name='configuration',
            field=models.TextField(default='{}', max_length=1048576),
        ),
    ]
