# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-11 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_external_data', '0011_externaldatasource_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldatarequest',
            name='can_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='externaldatarequest',
            name='last_emailed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
