# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-07 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_external_data', '0012_auto_20191210_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldatarequestfile',
            name='skipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
