# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-10 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_external_data', '0013_externaldatarequestfile_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldatarequest',
            name='extras',
            field=models.TextField(default='{}', max_length=1048576),
        ),
    ]
