# pylint: skip-file
# Generated by Django 3.2.12 on 2022-03-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_external_data', '0014_externaldatarequest_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldatasource',
            name='upload_extension',
            field=models.CharField(default='zip', max_length=64, null=True),
        ),
    ]
