name: passive-data-kit-external-data

services:
  db:
    image: postgis/postgis:16-3.4
    hostname: db
    volumes:
      - passive-data-kit-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    healthcheck:
      test: "psql -U ${PG_USER} -d ${PG_DB} -c 'SELECT PostGIS_Version();'"
      interval: 1s
      timeout: 5s
      retries: 10

  django:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/django/Dockerfile
    env_file: .env
    command: bash /app/run.sh
    volumes:
      - passive-data-kit-media:/app/media
      - passive-data-kit-static:/app/static
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl -s http://django:${DJANGO_WEB_PORT}/admin/login/ | grep -q "Django administration"
      interval: 15s
      timeout: 30s
      retries: 10
      start_period: 30s

  nginx:
    image: nginx
    env_file: .env
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - passive-data-kit-media:/app/media
      - passive-data-kit-static:/app/static
    ports:
      - "${NGINX_WEB_PORT}:${NGINX_WEB_PORT}"
    environment:
      - NGINX_WEB_HOST=${NGINX_WEB_HOST}
      - NGINX_WEB_PORT=${NGINX_WEB_PORT}
      - DJANGO_WEB_PORT=${DJANGO_WEB_PORT}
    depends_on:
      django:
        condition: service_healthy

  cron:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/cron/Dockerfile
    env_file: .env
    command: bash /app/run.sh
    volumes:
      - passive-data-kit-media:/app/media
      - passive-data-kit-static:/app/static
    depends_on:
      django:
        condition: service_healthy

volumes:
  passive-data-kit-db:
  passive-data-kit-media:
  passive-data-kit-static:
